### ISSUE TITLE
  note: This error originates from a subprocess, and is likely not a problem with pip.

### ISSUE THREAD

**Issue by ghost** [BluCodeGH/bedrock#18]
error: Command "aarch64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-aarch64-3.1/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-aarch64-3.1/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.10 -Ibuild/src.linux-aarch64-3.1/numpy/core/src/private -Ibuild/src.linux-aarch64-3.1/numpy/core/src/npymath -Ibuild/src.linux-aarch64-3.1/numpy/core/src/private -Ibuild/src.linux-aarch64-3.1/numpy/core/src/npymath -Ibuild/src.linux-aarch64-3.1/numpy/core/src/private -Ibuild/src.linux-aarch64-3.1/numpy/core/src/npymath -c build/src.linux-aarch64-3.1/numpy/core/src/multiarray/scalartypes.c -o build/temp.linux-aarch64-3.10/build/src.linux-aarch64-3.1/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.linux-aarch64-3.10/build/src.linux-aarch64-3.1/numpy/core/src/multiarray/scalartypes.o.d" failed with exit status 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> numpy
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by BluCodeGH** [comment]
This is a problem with your python installation trying to install numpy, not an issue with bedrock.
