### ISSUE TITLE
Question, sorry for using issues do not know how to contact developer:

### ISSUE THREAD

**Issue by BroomSalesman** [BluCodeGH/bedrock#22]
Hello, hope you're having a great day (and life).

I wanted to know, will this work with Minecraft education edition? 

Thanks, and once again sorry for using the issues section for asking a question.

And I mean using this in the normal way with minecraft education edition, not using it with the built in coding inside of it (I am not using that because it cannot import modules, which I need for what I am trying to make for a computer science final project)

**Comment by BluCodeGH** [comment]
I haven't updated this library in a long time so it might not support recent versions of education edition, but the level storage format is identical to "normal" bedrock so it may be update-able.

**Comment by BroomSalesman** [comment]
ok
