### ISSUE TITLE
Hope to add automatically create chunks feature

### ISSUE THREAD

**Issue by Northern-OceanS** [BluCodeGH/bedrock#6]
When the program is tempting to set blocks on a chunk didn't exist, the program will raise 'Chunk at xxx, xxx does not exist.'. Hope to add a feature which can automatically create empty chunks that filled with air, or superflat.

**Comment by BluCodeGH** [comment]
Unfortunately, Minecraft's internal chunk format is complex and not documented; the library currently only touches the parts it needs to and doesn't change or understand the rest. Implementing this would require it to have a full understanding of the chunk format which is out of the current scope.
