### ISSUE TITLE
Can the chunk be removed to restore the terrain?

### ISSUE THREAD

**Issue by XetPy1030** [BluCodeGH/bedrock#9]

**Comment by BluCodeGH** [comment]
This isn't explicitly supported but you can dig into the leveldb using `bedrock`'s internals to deleted all the information associated with the chunk (keys starting with `Chunk.keyBase`).

**Comment by XetPy1030** [comment]
Yes thank you. This is how I did it (changed bedrock/bedrock.py):
  def delete_chunk(self, x, y):
    o = [b",", b"-", b"1", b"2", b"6", b";", b"v"]
    for i in o:
      ldb.delete(self.db, struct.pack("<ii", x, y)+i)

**Comment by XetPy1030** [comment]
Yes thank you. This is how I did it (changed bedrock/bedrock.py(class World)):
  def delete_chunk(self, x, y):
    o = [b",", b"-", b"1", b"2", b"6", b";", b"v"]
    for i in o:
      ldb.delete(self.db, struct.pack("<ii", x, y)+i)
